select HOSPITALS.HOSPITAL_NAME, HOSPITALS.AVAILABILITY, count(DoCTORS.DOCTOR_ID) as "Количество врачей", TYPES_HOSPITAL.TYPE_NAME
from hospitals
join DOCTORS on HOSPITALS.HOSPITAL_ID = DOCTORS.HOSPITAL_ID
right outer join DOCTOR_SPECIALTIES on DOCTORS.DOCTOR_ID = DOCTOR_SPECIALTIES.DOCTOR_ID
join TYPES_HOSPITAL on HOSPITALS.TYPE_ID = TYPES_HOSPITAL.TYPE_ID
join PROFILE_WORKING_HOURS on HOSPITALS.WORKING_HOURS_ID = PROFILE_WORKING_HOURS.PROFILE_WORKING_HOURS_ID
where (HOSPITALS.DELETE_DT is null) and (DOCTOR_SPECIALTIES.SPECIALTY_ID = 1)
group by HOSPITAL_NAME, hospitals.AVAILABILITY, HOSPITALS.HOSPITAL_NAME, TYPES_HOSPITAL.TYPE_ID, TYPES_HOSPITAL.TYPE_NAME
order by TYPES_HOSPITAL.TYPE_ID, count(DOCTORS.DOCTOR_ID) desc; -- НЕ ДОДЕЛАНО, НЕ ПРИДУМАЛ РАБОТОСПОСОБНУЮ ПРОВЕРКУ ВРЕМЕНИ


