select *
from doctors
join QUALIFICATIONS on DOCTORS.QUALIFICATION_ID = QUALIFICATIONS.QUALIFICATION_ID
join AREAS  on AREAS.AREA_ID = DOCTORS.AREA_ID
where (DOCTORS.DELETE_DT is null) and (DOCTORS.HOSPITAL_ID = 1)
order by QUALIFICATION_LEVEL desc, (case when DOCTORS.AREA_ID = 2 then 1 else 2 end);
