select doctors.DOCTOR_NAME, HOSPITAL_ID, QUALIFICATION_NAME, AREA_NAME
from doctors
join QUALIFICATIONS on DOCTORS.QUALIFICATION_ID = QUALIFICATIONS.QUALIFICATION_ID
join AREAS  on AREAS.AREA_ID = DOCTORS.AREA_ID
where (DOCTORS.DELETE_DT is null) and (DOCTORS.HOSPITAL_ID = 1)
order by QUALIFICATION_LEVEL desc, (case when DOCTORS.AREA_ID = 1 then 1 else 2 end); -- 1 то участок пациента
