SELECT DISTINCT SPECIALITY_NAME
FROM specialties
inner join DOCTOR_SPECIALTIES on SPECIALTIES.SPECIALTY_ID = DOCTOR_SPECIALTIES.SPECIALTY_ID
inner join DOCTORS on DOCTOR_SPECIALTIES.DOCTOR_ID = DOCTORS.DOCTOR_ID
inner join HOSPITALS on DOCTORS.HOSPITAL_ID = HOSPITALS.HOSPITAL_ID
WHERE (SPECIALTIES.DELETE_DT IS NULL) and (DOCTORS.DELETE_DT is null) and (HOSPITALS.DELETE_DT is null);




