select doctors.DOCTOR_NAME, ID_HOSPITAL, QUALIFICATION_NAME, AREA_NAME
from doctors
join QUALIFICATIONS on DOCTORS.ID_QUALIFICATION = QUALIFICATIONS.ID_QUALIFICATION
join AREAS  on AREAS.ID_AREA = DOCTORS.ID_AREA
where (DOCTORS.DELETE_DT is null) and (DOCTORS.ID_HOSPITAL = 1)
order by QUALIFICATION_LEVEL desc, (case when DOCTORS.ID_AREA = 1 then 1 else 2 end); -- 1 то участок пациента
