create table CHESNOKOV_SE.regions
(
    id_region number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    region_name char(120) not null
);


create table CHESNOKOV_SE.cities
(
    id_city number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    city_name char(100) not null,
    id_region number not null
        references CHESNOKOV_SE.regions(id_region)
);


create table CHESNOKOV_SE.med_organizations
(
    id_med_organization number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    organization_name char(120) not null,
    id_city number not null
        references CHESNOKOV_SE.cities(id_city)
);


create table CHESNOKOV_SE.types_hospital
(
    id_type number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    type_name char(40) not null
);


create table CHESNOKOV_SE.areas
(
    id_area number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    area_name char(70) not null
);


create table CHESNOKOV_SE.qualifications
(
    id_qualification number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    qualification_name char(60) not null,
    qualification_level number not null
);


create table CHESNOKOV_SE.users
(
    id_user number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    login char(50) not null
);


create table CHESNOKOV_SE.genders
(
    id_gender number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    gender char(20) not null
);


create table CHESNOKOV_SE.specialties
(
    id_specialty number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    speciality_name char(50) not null,
    required_min_age number not null,
    required_max_age number not null,
    delete_dt date
);


create table CHESNOKOV_SE.gender_specialties
(
    id_gender number not null
        references CHESNOKOV_SE.genders(id_gender),
    id_speciality number not null
        references chesnokov_se.specialties(ID_SPECIALTY)
)


create table CHESNOKOV_SE.patients
(
    id_patient number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    surname char(50) not null,
    name char(50) not null,
    middle_name char(50),
    date_birth date not null,
    id_gender number not null
        references CHESNOKOV_SE.genders(id_gender),
    phone_number number(11),
    id_area number not null
        references CHESNOKOV_SE.areas(id_area),
    id_user number not null
        references CHESNOKOV_SE.users(id_user)
);


create table CHESNOKOV_SE.documents
(
    id_document number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    name char(50) not null
)


create table CHESNOKOV_SE.documents_numbers
(
    id_document_number number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    id_patient number
        references  CHESNOKOV_SE.patients(id_patient),
    id_document number
        references  CHESNOKOV_SE.documents(id_document),
    value varchar2(50)
)


create table CHESNOKOV_SE.working_time
(
    id_time number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    day number not null, -- номер дня недели
    begin_time timestamp not null,
    end_time timestamp not null,
    id_hospital number not null
);


create table CHESNOKOV_SE.hospitals
(
    id_hospital number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    hospital_name char(60) not null,
    id_organization number not null
        references CHESNOKOV_SE.med_organizations(id_med_organization),
    id_type number not null
        references CHESNOKOV_SE.types_hospital(id_type),
    delete_dt date,
    availability number not null
);


create table CHESNOKOV_SE.doctors
(
    id_doctor number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    id_hospital number not null
        references CHESNOKOV_SE.hospitals(id_hospital),
    id_area number not null
        references CHESNOKOV_SE.areas(id_area),
    id_qualification number not null
        references CHESNOKOV_SE.qualifications(id_qualification),
    doctor_name char(50) not null,
    salary number,
    education varchar2(100),
    delete_dt date
);


create table reviews
(
    id_review number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    id_doctor number not null
        references CHESNOKOV_SE.doctors(id_doctor),
    review varchar2(300),
    rating number not null
)


create table CHESNOKOV_SE.talons
(
    id_talon number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    delete_dt date,
    start_date date not null,
    end_date date not null,
    id_doctor number not null
        references CHESNOKOV_SE.doctors(id_doctor),
    availability number not null
);


create table CHESNOKOV_SE.journal
(
    id_jornal number GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    id_patient number not null
        references CHESNOKOV_SE.patients(id_patient),
    datetime date not null,
    id_talon number not null
        references CHESNOKOV_SE.talons(id_talon),
    delete_dt date,
    availability number not null
);


create table CHESNOKOV_SE.doctor_specialties
(
    id_doctor number not null
        references CHESNOKOV_SE.doctors(id_doctor),
    id_specialty number not null
        references CHESNOKOV_SE.specialties(id_specialty)
);


